apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapiserver
  namespace: default
  labels:
    k8s-app: nodeapiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nodeapiserver
  template:
    metadata:
      name: nodeapiserver
      labels:
        k8s-app: nodeapiserver
    spec:
      containers:
      - name: nodeapiserver
        image: ghcr.io/dekeyrej/nodeapiserver:latest
        imagePullPolicy: Always
        resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        envFrom:
          - secretRef:
              name: matrix-secrets
      imagePullSecrets:
        - name: ghcr-login-secret
        # volumeMounts:
        #   - name: secret-volume
        #     mountPath: /home/node/app/config
        #     readOnly: true
        # securityContext:
        #   privileged: false
      # volumes:
      #   - name: secret-volume
      #     secret:
      #       secretName: matrix-secrets