apiVersion: v1
kind: Service
metadata:
  name: nodeapiserver
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    name: nodeapi
  selector:
    k8s-app: nodeapiserver
